image: maven:3.5.4

stages:
  - prepare
  - build
  - test
  - package
  - release
  - tag
  - deploy
  - mirror

variables:
  MAVEN_CLI_OPTS: "-s .m2/settings.xml"
  MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"
  GIT_SUBMODULE_STRATEGY: recursive
  CLOUDSTACK_VERSION: "4.11.1.0"
  UPSTREAM_REPOSITORY: "git@github.com:bwsw/cloud-plugin-kv-storage.git"
  UPSTREAM_BRANCH: "master"
  DOCKER_IMAGE: "$CI_REGISTRY_IMAGE/simulator:$CI_COMMIT_REF_SLUG"
  DOCKER_IMAGE_LATEST: "$CI_REGISTRY_IMAGE/simulator:latest"
  DOCKER_PLUGIN_PATH: "target/cloud-plugin-kv-storage-*-shaded.jar"
  DOCKER_PLUGIN_ARTIFACT: "cloud-plugin-kv-storage.jar"

cache:
  paths:
    - .m2/repository/
    - target/

prepare:
  stage: prepare
  before_script:
    - cd cloudstack
    - git checkout "$CLOUDSTACK_VERSION"
  script:
    - cd .. && mvn $MAVEN_CLI_OPTS validate || (cd cloudstack && mvn -Pdeveloper -DskipTests clean install)
    - rm $DOCKER_PLUGIN_PATH || true
  tags:
    - build-in-docker
    - cs-eco-builder

build:
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS clean compile
  tags:
    - build-in-docker
    - cs-eco-builder

test:
  stage: test
  script:
    - mvn $MAVEN_CLI_OPTS test
  tags:
    - build-in-docker
    - cs-eco-builder

package:
  stage: package
  variables:
    GIT_SUBMODULE_STRATEGY: none
  script:
    - mvn $MAVEN_CLI_OPTS package
  artifacts:
   name: "$CI_COMMIT_REF_SLUG"
   paths:
     - $DOCKER_PLUGIN_PATH
  tags:
    - build-in-docker
    - cs-eco-builder

release:
  stage: release
  variables:
    GIT_SUBMODULE_STRATEGY: none
  cache: {}
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_JOB_TOKEN $CI_REGISTRY
  script:
    - cp $DOCKER_PLUGIN_PATH "simulator/$DOCKER_PLUGIN_ARTIFACT"
    - docker build -t $DOCKER_IMAGE --build-arg PLUGIN_PATH=$DOCKER_PLUGIN_ARTIFACT simulator
    - docker push $DOCKER_IMAGE
  dependencies:
    - package
  tags:
    - build-as-docker
    - cs-eco-builder

tag-master:
  stage: tag
  variables:
    GIT_SUBMODULE_STRATEGY: none
  cache: {}
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_JOB_TOKEN $CI_REGISTRY
  script:
    - docker tag $DOCKER_IMAGE $DOCKER_IMAGE_LATEST
    - docker push $DOCKER_IMAGE_LATEST
  only:
    - master
  tags:
    - build-as-docker
    - cs-eco-builder

deploy:
  stage: deploy
  script:
    - mvn $MAVEN_CLI_OPTS deploy
  tags:
    - build-in-docker
    - cs-eco-builder
  only:
    - master

mirror-master:
  stage: mirror
  variables:
    GIT_SUBMODULE_STRATEGY: none
    GIT_STRATEGY: clone
  cache: {}
  only:
    - master
  script:
    - mkdir -p ~/.ssh
    - echo $GITHUB_MIRROR_PRIVATE | base64 -d > ~/.ssh/id_rsa
    - echo $GITHUB_MIRROR_PUBLIC > ~/.ssh/id_rsa.pub
    - ssh-keyscan -t rsa,dsa,ecdsa github.com >> ~/.ssh/known_hosts
    - chmod -R go-rwx ~/.ssh
    - git remote add mirror $UPSTREAM_REPOSITORY
    - git remote show mirror
    - git fetch mirror
    - git push --progress mirror HEAD:$UPSTREAM_BRANCH
  tags:
    - build-in-docker
    - cs-eco-builder
